title: "Yang's personal website"
description: ""
author: "Z. Yang"
theme: minima
url: "https://koar-kreate.github.io"
baseurl: ""

navigation:
  - title: Home
    url: /
  - title: Research
    url: /research
  - title: Education
    url: /education

footer: "© 2024 Zhixian Yang | All rights reserved."
